server {
    listen 80;
    root /usr/share/nginx/html;

    location = / {
        try_files /index.html =404;
    }

    location = /editor {
        try_files /rehab_rule_editor.html =404;
    }

    location /static/ {
    }

    location / {
        return 404;
    }
}
